import type {
  KVNamespace,
  R2Bucket,
  D1Database,
} from "@cloudflare/workers-types";

// Generated by Wrangler by running `wrangler types`

export interface Env {
  KV: KVNamespace;
  R2: R2Bucket;
  D1: D1Database;
  ASSETS: Fetcher;
}
